make the skills and projects dynamically and customizable
RyanFitzgerald/devportfolio pull request #148
Opened 2022-08-25 17:21 UTC by abdellatif-laghjaj

This change improves the abillity of the user to easily customize the skills and projects data, by adding and changing a JSON file

2022-08-26 07:18 UTC, x9nico requested changes
Maybe you could remove the divs you commented at line 152 to 163 in index.html file ? Like that, the code will be more clean up and comprehensive :)

2022-08-26 15:06 UTC, abdellatif-laghjaj commented
Done ✔️

2022-08-26 18:50 UTC, x9nico approved these changes

2023-11-24 23:46 UTC, x9nico approved these changes

2024-07-04 19:46 UTC, x9nico approved these changes

2024-07-08 19:50 UTC, closed without merging